site_name: Syr
repo_url: "https://github.com/dmikey/syr"
copyright: "Syr is licensed under the <a href='https://github.com/dmikey/syr/blob/master/LICENSE'>MIT license"
theme: cinder
site_dir: docs
docs_dir: docsmd
google_analytics: ['UA-111449876-1', 'auto']
copyright: Derek M. Anderson